#!/bin/bash
set -e
set -u
set -x

MYSQL_ROOT_PASSWORD=`tr -dc A-Za-z0-9_ < /dev/urandom | head -c 20 | xargs`

echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" > env
echo "KNOWN_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> env
echo "MAIL_PASS=${MAIL_PASS}" >> env
echo "MAIL_USER=${MAIL_USER}" >> env
echo "MAIL_HOST=${MAIL_HOST}" >> env
echo "MAIL_PORT=${MAIL_PORT}" >> env
echo "MAIL_SECURE=starttls" >> env
